import type { ComponentType } from 'react'
import { MaskedAttentionAnim, MultiheadAttentionAnim, KVCacheAnim } from './transformer-anims'
import { FlashAttentionAnim, PagedAttentionAnim, MoEAnim } from './optimization-anims'
import { QuantizationAnim, SparseAttentionAnim, DistillationAnim, SpeculativeDecodingAnim } from './tradeoff-anims'
import {
  RLHFAnim,
  ChainOfThoughtAnim,
  ToolUsageAnim,
  TreeOfThoughtAnim,
  ContextEngineeringAnim,
  AIAgentsAnim,
  MCPAnim,
} from './reasoning-agent-anims'
import {
  WhatIsAIAnim,
  WhatIsVectorAnim,
  WhyVectorsAnim,
  VectorsInAIAnim,
  SimilarityDistanceAnim,
  LLMIntroAnim,
  CourseRoadmapAnim,
} from './intro-anims'
import {
  KDTreeAnim,
  AnnoyAnim,
  HNSWAnim,
  VectorDBAnim,
  TokenizationAnim,
  EmbeddingsAnim,
  TransformerFlowAnim,
  QKVAnim,
  WeightMatricesAnim,
  ParametersAnim,
  AttentionMechanismAnim,
  SoftmaxAnim,
  LayerNormAnim,
  FeedForwardAnim,
  PredictionAnim,
  GenericConceptAnim,
} from './foundation-anims'
import {
  ResidualAnim,
  RoPEAnim,
  GQAAnim,
  BertGptAnim,
  BackpropAnim,
  CrossEntropyAnim,
  LoRAAnim,
  PrefillDecodeAnim,
  TokenSamplingAnim,
  RAGAnim,
  DPOAnim,
  PositionalEncodingAnim,
  ALiBiAnim,
  CrossAttentionAnim,
  AutoregressiveAnim,
  GradientDescentAnim,
  AdamAnim,
  PrefixCacheAnim,
  TensorParallelAnim,
  BeamSearchAnim,
  ModernLLMAnim,
} from './advanced-anims'

type AnimComponent = ComponentType<{ step: number }>

const registry: Record<string, AnimComponent> = {
  'what-is-ai': WhatIsAIAnim,
  'what-is-vector': WhatIsVectorAnim,
  'why-vectors': WhyVectorsAnim,
  'vectors-in-ai': VectorsInAIAnim,
  'similarity-distance': SimilarityDistanceAnim,
  'llm-introduction': LLMIntroAnim,
  'course-roadmap': CourseRoadmapAnim,
  'kd-tree': KDTreeAnim,
  annoy: AnnoyAnim,
  hnsw: HNSWAnim,
  'vector-databases': VectorDBAnim,
  tokenization: TokenizationAnim,
  embeddings: EmbeddingsAnim,
  'transformer-flow': TransformerFlowAnim,
  'q-k-v': QKVAnim,
  'wq-wk-wv': WeightMatricesAnim,
  parameters: ParametersAnim,
  'attention-mechanism': AttentionMechanismAnim,
  softmax: SoftmaxAnim,
  'layer-normalization': LayerNormAnim,
  'feed-forward': FeedForwardAnim,
  prediction: PredictionAnim,
  'masked-attention': MaskedAttentionAnim,
  'multihead-attention': MultiheadAttentionAnim,
  'kv-cache': KVCacheAnim,
  'flash-attention': FlashAttentionAnim,
  'paged-attention': PagedAttentionAnim,
  'mixture-of-experts': MoEAnim,
  quantization: QuantizationAnim,
  'sparse-attention': SparseAttentionAnim,
  'slm-distillation': DistillationAnim,
  'speculative-decoding': SpeculativeDecodingAnim,
  'rlhf-reasoning': RLHFAnim,
  'chain-of-thought': ChainOfThoughtAnim,
  'tool-usage': ToolUsageAnim,
  'tree-of-thought': TreeOfThoughtAnim,
  'context-engineering': ContextEngineeringAnim,
  'ai-agents': AIAgentsAnim,
  'model-context-protocol': MCPAnim,
  'residual-connections': ResidualAnim,
  rope: RoPEAnim,
  'gqa-mqa': GQAAnim,
  'bert-vs-gpt': BertGptAnim,
  backpropagation: BackpropAnim,
  'cross-entropy-loss': CrossEntropyAnim,
  'lora-finetuning': LoRAAnim,
  'prefill-decode': PrefillDecodeAnim,
  'token-sampling': TokenSamplingAnim,
  rag: RAGAnim,
  dpo: DPOAnim,
  'absolute-positional-encoding': PositionalEncodingAnim,
  alibi: ALiBiAnim,
  'cross-attention': CrossAttentionAnim,
  'autoregressive-generation': AutoregressiveAnim,
  'teacher-forcing': AutoregressiveAnim,
  'gradient-descent': GradientDescentAnim,
  'adam-optimizer': AdamAnim,
  'gelu-swish-ffn': FeedForwardAnim,
  'output-projection-wo': MultiheadAttentionAnim,
  'prefix-cache': PrefixCacheAnim,
  'tensor-parallelism': TensorParallelAnim,
  'beam-search': BeamSearchAnim,
  'logits-perplexity': CrossEntropyAnim,
  'hallucination-safety': RAGAnim,
  'modern-llm-architectures': ModernLLMAnim,
}

export function getAnimationForConcept(id: string): AnimComponent {
  return registry[id] ?? GenericConceptAnim
}
